sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dheeraj100/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dheeraj100/react-test npm test

after_success:
  - docker build -t dheeraj100/multi-client ./client
  - docker build -t dheeraj100/multi-nginx ./nginx
  - docker build -t dheeraj100/multi-server ./server
  - docker build -t dheeraj100/multi-worker ./worker
  # Log in to the docker CLI
  - echo "\$DOCKER_PASSWORD" | docker login -u "\$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dheeraj100/multi-client
  - docker push dheeraj100/multi-nginx
  - docker push dheeraj100/multi-server
  - docker push dheeraj100/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: 'us-east-1'
 # app: 'multi-docker'
  #env: 'MultiDocker-env'
  #bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  #bucket_path: 'docker-multi'
  #on:
  #  branch: main
  #access_key_id: $AWS_ACCESS_KEY
  #secret_access_key: $AWS_SECRET_KEY
